export const SEARCH_RESULT_ENTITY_HEIGHT = 215;
export const SEARCH_RESULT_ENTITY_SPACING = 25;
export const SEARCH_RESULT_FACETS_TRIMMED_COUNT = 4;
export const SEARCH_RESULT_OVERSCAN = 12;
export const SEARCH_RESULT_SCROLL_TO_TOP_AVAILABLE_AT = 5;
